### ISSUE TITLE
To- Do List

### ISSUE THREAD

**Issue by Magicode1** [PMPluginDevelopers/Plug-On#12]
Please try to get these things done, and when you finish, check them off.

Please don't use this for Communication, use the Slack team for that.

**To Do List**
- [ ] Create working PHP scripts
- [x] Beautify the HTML pages (Make them match with the new Pocketmine website) 
- [ ] Make a Sign Up/Sign in Page
- [x] Organize (Make directories for certain things, etc.)
- [ ] Voting System (Users vote for plugins and the more votes the plugins get, the higher they are on the list)
- [ ] Possibly a Forums? Only for each individual plugin for users to ask questions/submit bugs
- [ ] Author Pages (Shows information on the author and all or their plugins)
- [ ] Plugin Search Bar
- [ ] Customization plugin posting (Ability for authors to customize their plugins page with description, images, etc.)
- [ ] Ability for Authors to upload plugin updates (New plugin releases)
- [ ] 1-5 Star Review System (Or not if we just want to do voting)
- [ ] Different Categories? World Management, Fun, Mechanics, etc.

If we get these things done, we will be more than ready for the 1.0.0 release 👍

**Comment by Edwardthedog2** [comment]
Does a homepage still need to be made? I can get right on that. You can put HTML inside php files right?

**Comment by Magicode1** [comment]
A homepage has already been made. It is in /modules/archive/archivemodule.php

**Comment by hiilikewiki** [comment]
Please use the projects now to replace this.

**Comment by Thunder33345** [comment]
closed, moved to https://github.com/PMPluginDevelopers/Plug-On/projects/1

**Comment by hiilikewiki** [comment]
Just to stop people thinking we had released
