### ISSUE TITLE
Invite Me!

### ISSUE THREAD

**Issue by ghost** [PMPluginDevelopers/Plug-On#22]
Can you guys invite me to the Slack Group?

My Email is: admin@dc4.us

I can really help you guys out I know many programming languages.

HTML5,CSS3,PHP,JAVASCRIPT,BATCH,SHELL,C++

**Comment by hiilikewiki** [comment]
Hello, thank you for taking an interest in our project. I will contact @Magicode1, our admin for slack. Meanwhile, feel free to use our forums and visit our project website at plug-on.tk.

**Comment by SOF3** [comment]
HTML5 and CSS3 aren't programming languages. They are the languages that _distract_ people from programming, which I personally call them anti-programming languages.

**Comment by hiilikewiki** [comment]
@SOF3 We use HTML5 and CSS3. Ok, maybe it could be reworded.

**Comment by SOF3** [comment]
@archie426 I know, but they aren't programming languages. They are markup languages, for user interface. They, well, maybe not really distract programming all the time, but are a form of output of programming, not the process of programming itself.

**Comment by hiilikewiki** [comment]
@SOF3 That is very true. But just because he hasn't worded his sentence properly doesn't mean that he can't join the organisation. But you have a good point.

**Comment by SOF3** [comment]
@archie426 when did I say he shouldn't be allowed to join the organization?

**Comment by hiilikewiki** [comment]
@SOF3 Oh it just sounded like you were. Sorry

**Comment by hiilikewiki** [comment]
I will close this. We have invited you to GitHub, and I am not sure about slack
