### ISSUE TITLE
[Discussion] General Discussion

### ISSUE THREAD

**Issue by Thunder33345** [PMPluginDevelopers/Plug-On#9]
Ok since we all rarely discuss most things at least to me i guess
So lets get this straight i would like to see how other contributor envision this to be or prefer how this would be
Personally: it would be consist of home,upload,list page
my original idea would be that we will have a SQLITE3(NOT MYSQL)(since SQLITE is free unlike SQLITE) database that stores user,voting,plugin data itself etc
ok but before i went on rambling i would like to see what other of you guys have to say

**Comment by Magicode1** [comment]
My General Thoughts:

I totally agree. I had the same homepage layout as you, except I also wanted to add an Authors page.

I also like the idea of using SQLITE3, can you help get that set up? 

Me and Edward where not communicating at all, just changing stuff and reading each others commits 😄 

I made a To Do List issue, you can edit it if you want

Also, I will make you an Owner

What if we make some teams to divvy up the work?

It would also help to have more contributors, do you know anyone who would want to help? 😋

**Comment by Thunder33345** [comment]
well for author it would be better to be like
plugin.php?id=(plugin ID) the plugin php will do the work for sorting out data and so on
sure but i would just be happy if i have write access
also about contributors it would helpful if we have a more somewhat clearer shared goal
so we wont end up with a lot people trying to do the same thing with different approaches which would not be helpful

**Comment by Magicode1** [comment]
Agreed. I gave you Ownership and write access 

Maybe we make our goals and approaches in the Wiki?

**Comment by Thunder33345** [comment]
ok i think you could do that with the wiki
about the SQLITE we dont necessary need to set it up as long as the host support it

**Comment by EdwardHamHam** [comment]
Is the plan still to use infinityfree.net? I've used them, I know they support MySQL, however I'm not sure about SQLITE.

**Comment by Thunder33345** [comment]
I dislike SQL for several reasons some host limits space or how much "databases" you can have and for SQLITE it cant be limited(other than storage limit) it just need the SQLITE library to function

**Comment by Magicode1** [comment]
InfinityFree.net is a good option, I assume there's no better ones out there? 

Do we want out own domain?

Github also supports making websites from repositories, but they are pretty limited on space.

**Comment by Thunder33345** [comment]
i THINK github allows you to redirect it to DNS like settings? where you just need to point it toward github's DNS and they will sort it for you
not very sure will go on and research a bit

**Comment by Magicode1** [comment]
Same, I am unsure of their features

**Comment by Thunder33345** [comment]
Update: wasted more time than i like researching i don't know
maybe we just have to use git pages to redirect it toward our host IP
meanwhile i found something https://thunder33345test.github.io/PageTest/ some browsers dont like it tho and very hacky

**Comment by EdwardHamHam** [comment]
Wait. I'm afraid I have some bad news. I just read Infinity Free's terms of service. Part of it says this:

> upload, post, email, transmit or otherwise make available any material that is of keylogging / proxy service / irc / shell(s) if any type / file hosting / file sharing types.

In other words, we can't use them, because sharing the plugins counts as "file sharing". Looking at the rules of some other free hosts, it looks like the only web hosts without that limitation, are very limited free hosts, or paid web hosts.

**Comment by Magicode1** [comment]
I like the test page @Thunder33345 

Do either of you have access to your own server? If so we could use that.

I am going to research some more web hosts.

**Comment by Magicode1** [comment]
Ok, Some stuff on what I found:

https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

Github pages doesn't seem too secure. If we want to have a login system then maybe self-hosted or online hosting is better. 

It says we could use cloudflare but IDK how much more secure it will make it.

**Comment by Thunder33345** [comment]
Glad you catch that @Edwardthedog2 
we have a few valid options:
- simply use a paid host
- find a host that allow that
- use something to handle the files so we are not directly hosting that so technically we are consider an INDEXER then file sharer (cont for next reply)

**Comment by Thunder33345** [comment]
@Magicode1 i have my own server which i got for free but that is all i would have to make a subdomain or something to make it host there also remember [someone](http://forums.pocketmine.net/threads/a-new-place-to-post-plugins.18476/#post-172731) offer to sponsor the first month but that is not enough since we need to be self sufficent as possible

also github pages arent meant to be top tier security it is meant to just SHOW stuff like your project page or personal pages but not like for your important stuff that need to be threatened with security 
what we are doing is just essentially HACKING it since by 
- redirecting it to our site (recommended)
- IFRAMING our site (not so best practices)

they DONT serve PHP and they are not a webhost

**Comment by Magicode1** [comment]
A redirect might be the best bet then. 

No-ip would be a good option. They have a nice system, but you have to refresh it once a month in order for the Dynamic-DNS to stay active.

http://www.noip.com/

**Comment by Thunder33345** [comment]
depends
do you want it to be (something).github.io or yourname.(ddns from no-ip)
wait we could use (something).mcpe.me !!!!
(it somewhat suits more since we are about mcpe anyways right?)

**Comment by Magicode1** [comment]
Yeah! Thats what I was thinking!

**Comment by Thunder33345** [comment]
i guess we can "close" that issue about domain names
ok we still need to sort the issue about no file sharing

**Comment by Magicode1** [comment]
If you have a server, we could use noip for that server, then we wouldn't have to worry about file sharing restrictions.

**Comment by Thunder33345** [comment]
well it is a hosted server that i own but not very sure if they allow hosting

**Comment by Thunder33345** [comment]
oh wait never mind

> - Using your shared/reseller hosting as a file or image hosting service. VPS is exempt from this. (https://www.blueleafhosting.com/tos)

**Comment by Magicode1** [comment]
Ok

Sweet! Is it ok if we use it for this website??

**Comment by Thunder33345** [comment]
nope like my last reply
from what i seen most webhost does not allow it
but we could just try it anyways if we limit the size of each files so it wont be too critical OR just let some website to handler our plugins

**Comment by Magicode1** [comment]
We could try google drive. It has 15GB free. Just store the plugins there and have the website access them. It's secure, and if it gets full we could have a script that deletes the least voted/outdate plugins from the bottom of the list.
There is also an option to HOST from google drive, again possibly using the Noip

**Comment by Thunder33345** [comment]
i mean if we really strive to not violate the TOS we could
and if we are just hosting plugins it wont be too much of an headache we arent hosting videos so capacity wont be an issue
but it would help if we have other alternatives so i could investigate their APIS or just brute force it in
PS something like https://transfer.sh/ but store files longer like prefrebally forever will do the trick too

**Comment by Magicode1** [comment]
Alright, I will look into other options. I will let you guys know what I find. If you find anything be sure to tell us as well. 😃 

It might be beneficial to use google drive to host the files (Have an HTML/PHP script to upload the author's plugins to google drive) and then just use the download url inside a Download box on each plugins page

**Comment by EdwardHamHam** [comment]
Found something! We could use https://kloud51.com as the host. I've used them before, pretty good pricing, and very professional services. I've read their terms of service, and they have no rule against hosting a file sharing site on their web hosting plans. Read it at: https://kloud51.com/tos

**Comment by Magicode1** [comment]
Awesome! We would definitely have to use the Google Drive approach I mentioned earlier because of their storage size, but it looks like a really solid option!

I have to do some more research on it, but for now, I think it would be best to start working on the To-Do list at: https://github.com/PMPluginDevelopers/Plug-On/issues/8

We also have to keep in mind that we can't release the website until we've coded it as well 😋 

I'm so excited to get this up and running!

**Comment by EdwardHamHam** [comment]
Is there a way to have a website obtain the files from Google Drive?

**Comment by Thunder33345** [comment]
personally my idea is to store all author and dats on another sqlite table so it dosent matter as long as i can give them a download button to somewhere that the file stays permenant 
and good find @Edwardthedog2 but storage size is questionable but the 0.50$/M(6$) plan is something to keep in mind
personally i would like to have other options since the google drives api seems to no where be found or at least for me i prefer NOT using a libary if it is possible
i would go with external storage TBH if dealing with this size since we rather aim to keep the site running long with the artifect plugin of the past

**Comment by Thunder33345** [comment]
we would have to use API to upload files to THERE once player uploads them on our site so it looks like
User upload plugin -> our server API -> external storage API return link  -> server store link
user request -> our server give link to user -> user download from that link
now i think about if we can also ASK user to handel them by themself like tell them to give link but not good since it can be removed/do stuff on

**Comment by Magicode1** [comment]
There is a way. Google drive lets you make download links. You could simply put those links into a download button and it would download from google drive. It would also cut out a considerable amount of traffic data.

**Comment by Magicode1** [comment]
About the api... I have no idea. But there is a resource called google scripts:

https://ctrlq.org/code/19747-google-forms-upload-files

**Comment by Thunder33345** [comment]
hm nope we need PHP code that uploads it so we are basically middle man passing data to our external API
google seems fairly decent since it should be persistent and forever but their API is kinda over compeherensive for my liking
i am also in search for free alternative with free API nothing to loose really looking for possible alternatives
also this should be the last massage from me for the day at least while i sleep

**Comment by Thunder33345** [comment]
update; i think it is best of our interest to just store it ON site with a host that allows that so we dont need to deal with external APIS and remember plugin are only around KB

**Comment by Magicode1** [comment]
So we are still going through with this website, even with xBeastModes? I was thinking we could have more features, like author pages and leaderboards.

**Comment by Magicode1** [comment]
Yes, I agree, we just need to find a host with enough storage. 
Yeah plugins are super tiny. Even worst case scenario (Plugins all being 25kb) we could store 400 of them on 10mb

And I guess we will have more features, because our design is mostly crowd sourced, with plugins earning votes to get to the top.

**Comment by Thunder33345** [comment]
yes i personally would like to do that regardless of how it turns out it is a learning experience for me
but serious for a moment the issue with it was aparently there other people have the sort of same same idea(in a more general spectrum- a site to share plugins)
look at XBeast with his [plugin page](https://www.mcpefun.com/plugins) or SOFe with her [poggit](https://github.com/poggit/poggit) and mostlikely even more that we never notice

**Comment by Magicode1** [comment]
Yes, the thing that sets our site apart is our voting system. We don't have plugin reviewers, authors just post there plugins and they either get voted for to go up the list, and ones with the least votes go to the bottom

**Comment by Magicode1** [comment]
That's why we need to finish the PHP upload script so we can get working on the Plugin list

**Comment by Thunder33345** [comment]
yes and a useful [DORK](https://www.google.com/search?q=free+web+hosting+inurl%3A"%2Ftos"+-sharing&oq=free+web+hosting+inurl%3A"%2Ftos"+-sharing)(not the best on using dork but this should do the trick) should pull out host that did not say we cant file share (best to read their site to make sure they are free and did not use other kind of "unprediected" wording

**Comment by Thunder33345** [comment]
Come to conclusion that https://www.2freehosting.com/features.html would be our prefered host to deploy our work onto
they have no regulations against file sharing with 20 GB disk space that should do the trick

**Comment by Magicode1** [comment]
Sounds good. Now we just need a Domain.

**Comment by Thunder33345** [comment]
well that was surely a heck of a problems we are encountering
we could probably request plugon.mcpe.me for an easy solution
ALSO : the site will automatically be deactivated if it dosent have visitors for 30 days(like all free hosts)
ALSO : just notice that they uses PHP 5.4 as latest
i have a genius idea for a ping back mechanism to avoid that automatically doe

**Comment by Thunder33345** [comment]
actually i think all free host are out of order since their FTP wont work

**Comment by Magicode1** [comment]
So we can't do a free host?

**Comment by Thunder33345** [comment]
we may just have to use some cheap host

**Comment by Magicode1** [comment]
Alright. Who should sponsor? I can't spend any money on it ATM

**Comment by Thunder33345** [comment]
no idea TBH

**Comment by Magicode1** [comment]
Alright. Let's just start working on the code for now, we can keep working on this later

**Comment by Thunder33345** [comment]
we should
we are somewhat over worrying

**Comment by Magicode1** [comment]
Yeah 😃

**Comment by Magicode1** [comment]
Have you guys looked at the To - Do list? Do you think you could help with those items?

**Comment by EdwardHamHam** [comment]
Yes, I will try to work on an upload script, although I don't know how long it'll take.

**Comment by Magicode1** [comment]
Alright, thanks.

**Comment by Magicode1** [comment]
This discussion has moved to the Gitter chat. 

Please go to:
https://gitter.im/Plug-On/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
To chat with us about features and development!
